doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 80
#uses:
#    - django
#    - celery
#autodetect: yes
#requirements:
#    - deps/core.txt
#    - deps/test.txt
#ignore-paths:
#    - docs
#    - mypackage/vendor
#ignore-patterns:
#    - ^example/doc_.*\.py$
#    - (^|/)docs(/|$)
